### ISSUE TITLE
Add information how to find items and relationships 

### ISSUE THREAD

**Issue by fehrhart** [BiGCAT-UM/SPARQLTutorialBioSB2019#1]
At the moment there is only the possibility to search a term shown, maybe add a small chapter how to find the relationship network and the documentation to get an idea which terms and relationships are available and how exactly they are structured. 
E.g. looking for the school Douglas Adams went... Wikidata offers "educated by"...
looking for kind of "is biomarker for a disease", Wikidata offers "prognostic predictor"... 

That is especially important when changing to other databases with different tree/network structures.

(no necessity... could be a small upgrade)

**Comment by DeniseSl22** [comment]
Also added to [addendum](https://github.com/BiGCAT-UM/SPARQLTutorialBioSB2019/blob/master/Assignments/AddendumBioSb2019.md), with some more explanation on how to get relationships for entries of interest.
