### ISSUE TITLE
The label service is not standard SPARQL

### ISSUE THREAD

**Issue by andrawaag** [BiGCAT-UM/SPARQLTutorialBioSB2019#3]
The example given on a basic SPARQL query contains the SERVICE clause from WIkidata. This is not default SPARQL behaviour and more a wikidata hack. Based on the current text I would have as take home message that SERVICE is for getting labels. Which they are not. 

I would recommend rewriting the query using RDFS:label and FILTER clauses, which your SERVICE example is basically doing. 

Also the label service is really expensive, so if a query times out, this SERVICE example is the first to go to optimize.

**Comment by DeniseSl22** [comment]
Yes you are right, thank your for pointing this out! I didn't want to make things more complicated then they are. SERVICE is being used in (quite a lot of) example queries, so I want users to know what it is.
I'm making an addendum for the material, to add some Q&A (based on questions we got during the workshop), and with some additional explanation. This will fit right in :)/

**Comment by DeniseSl22** [comment]
Fixed with additional note in assignment one, and addendum in [Addendum Text](https://github.com/BiGCAT-UM/SPARQLTutorialBioSB2019/blob/master/Assignments/AddendumBioSb2019.md)
